
name: Deploy
'on':
  push:
    branches:
      - main

jobs:
  deploy:
    name: 'Deploy'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Clone project
        uses: actions/checkout@v2

      - name: Load Environment Variables
        run: |
          touch .env
          echo DATABASE_URL=${{ secrets.DATABASE_URL }} >> .env

      - name: Install dependencies
        run: yarn

      - name: Migrate DB
        run: yarn migrate:deploy
      
      - name: Generate Prisma Client
        run: yarn generate

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "write-it-backend"
          entrypoint: "./src/app.js"